/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Audit {
  'id' : bigint,
  'status' : AuditStatus,
  'timestamp' : Time,
  'leaseName' : string,
}
export type AuditStatus = { 'pending' : null } |
  { 'scanning' : null } |
  { 'complete' : null };
export interface Finding {
  'title' : string,
  'clauseExcerpt' : string,
  'explanation' : string,
  'category' : FindingCategory,
}
export type FindingCategory = { 'hidden_cost' : null } |
  { 'tenant_responsibility' : null } |
  { 'illegal_clause' : null };
export type Time = bigint;
export interface UserProfile { 'displayName' : string, 'plan' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAudit' : ActorMethod<[string], bigint>,
  'getAuditFindings' : ActorMethod<[bigint], Array<Finding>>,
  'getAuditHistory' : ActorMethod<[], Array<Audit>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'init' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUserPlan' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];