/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FindingCategory = IDL.Variant({
  'hidden_cost' : IDL.Null,
  'tenant_responsibility' : IDL.Null,
  'illegal_clause' : IDL.Null,
});
export const Finding = IDL.Record({
  'title' : IDL.Text,
  'clauseExcerpt' : IDL.Text,
  'explanation' : IDL.Text,
  'category' : FindingCategory,
});
export const AuditStatus = IDL.Variant({
  'pending' : IDL.Null,
  'scanning' : IDL.Null,
  'complete' : IDL.Null,
});
export const Time = IDL.Int;
export const Audit = IDL.Record({
  'id' : IDL.Nat,
  'status' : AuditStatus,
  'timestamp' : Time,
  'leaseName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'plan' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAudit' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getAuditFindings' : IDL.Func([IDL.Nat], [IDL.Vec(Finding)], ['query']),
  'getAuditHistory' : IDL.Func([], [IDL.Vec(Audit)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'init' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserPlan' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FindingCategory = IDL.Variant({
    'hidden_cost' : IDL.Null,
    'tenant_responsibility' : IDL.Null,
    'illegal_clause' : IDL.Null,
  });
  const Finding = IDL.Record({
    'title' : IDL.Text,
    'clauseExcerpt' : IDL.Text,
    'explanation' : IDL.Text,
    'category' : FindingCategory,
  });
  const AuditStatus = IDL.Variant({
    'pending' : IDL.Null,
    'scanning' : IDL.Null,
    'complete' : IDL.Null,
  });
  const Time = IDL.Int;
  const Audit = IDL.Record({
    'id' : IDL.Nat,
    'status' : AuditStatus,
    'timestamp' : Time,
    'leaseName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'plan' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAudit' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getAuditFindings' : IDL.Func([IDL.Nat], [IDL.Vec(Finding)], ['query']),
    'getAuditHistory' : IDL.Func([], [IDL.Vec(Audit)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'init' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserPlan' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };